
const pageId=document.querySelector('meta[name="ts:pageId"]').getAttribute('value');if(pageId==='home'){setTimeout(()=>{const videos=document.getElementsByTagName('video');for(const video of videos){video.setAttribute('poster',video.getAttribute('deferred-poster'))}},500);}
if(pageId==='handbook'){let showSidebar=false;let showSearchInput=undefined;let searchString="";let searchStringOverride="";let oldSearchStringOverride=undefined;let oldSearchString=undefined;let searchResultGroups=[];const sidebarButton=document.querySelector('.hb-sidebar-button');const sidebarNav=document.querySelector('.hb-sidebar');const closeSidebarClickTarget=document.querySelector('.hb-close-sidebar-click-target');const searchButton=document.querySelector('.search-button');const searchButtonImage=searchButton.querySelector('img');const searchForm=document.getElementById('handbook-search');const searchInput=document.querySelector('.search');const handbookToolbarDiv=document.querySelector('.hb-toolbar');const handbookToolbarContentAreaDiv=handbookToolbarDiv.querySelector('.content-area');const handbookContainerDiv=document.querySelector('.hb-container');const handbookContentsForMarkdownDiv=document.querySelector('.hb-contents-md');const handbookContentsForSearchResultsDiv=document.querySelector('.hb-contents-search-results');const noSearchResultsMessage=document.getElementById('no-search-results-message');const lang=document.querySelector('meta[name="ts:lang"]').getAttribute('value');const langSubpath=lang==="en"?"":`${lang}/`;const isV2=document.querySelector('meta[name="ts:v"]').getAttribute('value')==='2';const REDIRECTS={'handbook/settings/general#appearance':'handbook/settings/appearance','handbook/settings/general#theme':'handbook/settings/appearance/#theme','handbook/settings/general#show-background-grid':'handbook/settings/appearance/#show-background-grid','handbook/text/text_layer#font-weight':'handbook/text/text_layer#font-style','handbook/settings/tools#pen-tilt-limits':'handbook/brushes/brush_settings#tilt-control-threshold','handbook/settings/general#pivot-editing-enabled':'handbook/settings/tools/#pivot-editing-enabled'}
if(isV2){REDIRECTS['handbook/colors/fill_tool#smooth']='handbook/settings/tools/#fill-smooth-edges'}
const currentPath=window.location.href.replace(".html","").replace('/#','#');for(const[fromPath,toPath]of Object.entries(REDIRECTS)){if(currentPath.endsWith(fromPath)&&!currentPath.endsWith(toPath)){const basePath=currentPath.replace(fromPath,"");const redirectPath=basePath+toPath;window.location.href=redirectPath;break;}}
const generatingPDFHandbook=window.location.search.includes("mode=pdf");if(generatingPDFHandbook){const rootDiv=document.getElementById('page-root')
rootDiv.classList.add('pdfgen');}
async function search(text){const module=await import('/search.js');return module.search(text,`/${langSubpath}handbook/search_index.json`);}
function refresh(){if(showSidebar){sidebarNav.classList.add('hb-sidebar-visible');}else{sidebarNav.classList.remove('hb-sidebar-visible');}
const searchParams=new URLSearchParams(window.location.search);const searchParamsQ=searchParams.get('q');if(searchStringOverride!==oldSearchStringOverride||searchParamsQ!==null){searchString=searchStringOverride||searchParamsQ;oldSearchStringOverride=searchStringOverride;}
if(searchString&&handbookContentsForMarkdownDiv.parentNode){handbookContainerDiv.removeChild(handbookContentsForMarkdownDiv);}else if(!searchString&&!handbookContentsForMarkdownDiv.parentNode){handbookContainerDiv.insertBefore(handbookContentsForMarkdownDiv,handbookContainerDiv.childNodes[2]);}
if(searchString&&!handbookContentsForSearchResultsDiv.parentNode){handbookContainerDiv.insertBefore(handbookContentsForSearchResultsDiv,handbookContainerDiv.childNodes[2]);}else if(!searchString&&handbookContentsForSearchResultsDiv.parentNode){handbookContainerDiv.removeChild(handbookContentsForSearchResultsDiv);}
if(searchString!==oldSearchString){if(searchString){search(searchString).then(results=>{let groups={};let orderedKeys=[];for(const result of results){let href=result.id;const anchorIndex=href.indexOf('#');if(anchorIndex>0){href=href.substring(0,anchorIndex);}
const pathComponents=href.split('/');const group=pathComponents[0];const page=pathComponents[1];const groupName=result.group;const pageName=result.page;const isOverviewPage=page==='overview';if(!groups[result.id]){groups[result.id]={group:groupName,page:pageName,isOverviewPage:isOverviewPage,entries:[]};orderedKeys.push(result.id);}
const resultGroup=groups[result.id];const preview=result.body!==""?result.body.substring(0,80)+"…":"";resultGroup.entries.push({href:result.id,title:result.title,preview:preview});}
searchResultGroups=[];for(const key of orderedKeys){searchResultGroups.push(groups[key]);}
refresh();});}else{searchResultGroups=[];}
oldSearchString=searchString;}
const hasSearchString=searchString!=null&&searchString!=="";const currentPath=window.location.pathname;const isRootHandbookPage=currentPath.endsWith(`/${langSubpath}handbook`)||currentPath.endsWith(`/${langSubpath}handbook/`)||currentPath.endsWith(`/${langSubpath}handbook/index.html`);if(showSearchInput===undefined){showSearchInput=hasSearchString||isRootHandbookPage;}
const searchIcon=showSearchInput?'/assets/images/cancel_search.svg':'/assets/images/search.svg';searchButtonImage.src=searchIcon;const hasSearchResults=searchResultGroups.length>0;if(showSearchInput&&!searchForm.parentNode){const focusedElement=document.activeElement;if(focusedElement!==searchInput){focusedElement.blur();}
searchForm.removeAttribute('hidden')
handbookToolbarContentAreaDiv.insertBefore(searchForm,handbookToolbarDiv.childNodes[3]);searchInput.focus();}else if(!showSearchInput&&searchForm.parentNode){searchInput.removeAttribute('autofocus')
handbookToolbarContentAreaDiv.removeChild(searchForm);}
if(searchString){while(handbookContentsForSearchResultsDiv.firstChild){handbookContentsForSearchResultsDiv.lastChild.remove();}
for(const group of searchResultGroups){for(const entry of group.entries){const pageName=group.isOverviewPage?group.group:group.page;const groupName=group.isOverviewPage?group.page:group.group;const isSubsection=entry.title!==group.page;const breadcrumbs=isSubsection?`${groupName} > ${pageName}`:groupName
const title=isSubsection?entry.title:pageName;const div=document.createElement('div');div.className='hb-search-result';const link=document.createElement('a');link.href=`/${langSubpath}handbook/${entry.href}`;link.onclick=()=>{searchStringOverride=undefined;refresh();return true;}
const h4=document.createElement('h4');h4.textContent=breadcrumbs;link.appendChild(h4);const h2=document.createElement('h2');h2.textContent=title;link.appendChild(h2);if(entry.preview){const p=document.createElement('p');p.textContent=entry.preview;link.appendChild(p);}
div.appendChild(link);handbookContentsForSearchResultsDiv.appendChild(div);}}
if(!hasSearchResults){handbookContentsForSearchResultsDiv.appendChild(noSearchResultsMessage);}}}
sidebarButton.onclick=()=>{showSidebar=!showSidebar;refresh();};closeSidebarClickTarget.onclick=()=>{showSidebar=false;refresh();};searchButton.onclick=()=>{showSearchInput=!showSearchInput;refresh();};let defaultSearchInputValue="";searchInput.defaultValue=defaultSearchInputValue;searchInput.oninput=()=>{searchStringOverride=searchInput.value;refresh();};const searchParams=new URLSearchParams(window.location.search);const searchParamsQ=searchParams.get('q');if(searchParamsQ!==null){searchInput.value=searchParamsQ;}
document.addEventListener('keydown',(event)=>{if(event.metaKey&&event.key==='p'){showSearchInput=true;searchInput.focus();searchInput.select();event.preventDefault();refresh();}});refresh();}